  - name: yum update
    shell: yum -y update
    asynac: 3600
  - name: Install Software
    yum: name={{ item }} state=latest
    with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - epel-release
      - python-pip
    ignore_errors: yes
  - name: yum-config-manager
    shell: yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
  - name: install docker-ce
    shell: yum makecache fast;yum -y install docker-ce
  - name: service docker start
    shell: service docker start
  - name: Install docker-compose
    shell: pip install --upgrade pip;pip install docker-compose